apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer
  namespace: kafka-integration
  labels:
    app: kafka-consumer
data:
  "BROKER_ADDRESS": "18.228.222.70:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: kafka-consumer
        image: "rudtux/consumer-py:latest"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: kafka-consumer
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
