apiVersion: v2
name: kube-prometheus-stack
version: 54.0.1
appVersion: v0.69.1
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.

dependencies:
- name: kube-prometheus-stack
  version: "54.0.1"
  repository: https://prometheus-community.github.io/helm-charts