kube-prometheus-stack:
  
  namespaceOverride: "monitoring"
  
  defaultRules:
    create: false

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 6h
      additionalScrapeConfigs:
        - job_name: 'kafka-server'
          static_configs:
          - targets: ['18.228.222.70:7071']

  grafana:
    enabled: true
    namespaceOverride: "monitoring"
    defaultDashboardsTimezone: utc
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          isDefault: true
          access: proxy
    adminUser: admin
    testFramework:
      enabled: false
    dashboardsConfigMaps:
      kafka: "kafka-metrics"